language: bash

env:
  global:
    - GIT_AUTHOR_EMAIL=bot@kstm.shinshu-u.ac.jp
    - GIT_AUTHOR_NAME=bot
    - HUGO_VERSION=0.82.0
    - secure: "U7kHLYIOphik2JBcVCdGjvjpcBgiAZ0jNLtLnNiqGe4X+cCM0QBv5e2JJfUfL/mFDVjBp9MPYzUpTLhvTATIOoxfJ0862cnp2azhPKiyfSSutd7H8bDL8vAsOOaH0trQB0qlBAho8iP02LaBBfuAWqdvsvEBTmiebOFp+ekqyiwBe4ieA6BGqG+lzULEd1opqwje5bf2gnCZYa6pdcKDkUTqca8zQj1Rvf5DOtX9lYtMY4Da+SKVeTOARINoJGYjlf7/ITa0fM+zMfxlJOOn3vPTzWA5mS/qc6THqamlK1lz1L8iBxUT2JLi1rE8Xg5Wk0SS7VdfSinA8aBXtgFg7377j110Rf6DUgTnl2E3jPbf6x8+auYE5rLaN0r0551eOlyM9R56FR0pbsmG6xJQRfmD/G9oCm6T1V6ETSysssIBBxxZ/Zeafh5r/yB1kVdku1cjsnnALyQ+Vs9ZMWNsI2txO9D2ej83/4Vfnm8siJK/Fo7w6KrkRs2y4nfEBoSCYQ8QXh+bHICj7CfE4B2X3KfonwJUqQMnFbmot9KqPXEC1obcw3pE0NWzml0yIhwsJFFUOvgEUJYSIhKvAkxr4t9JW6N4ZshX4zZeb0oQJs4lgDvODPhBGBElnDMASIsOkcJbwXM1/gY/LsjWpBvw8fIXzy1flinAOkX0LUahUsA="
    - GIT_URL=https://${GIT_TOKEN}@github.com/kstm-su/blog.git

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

before_deploy:
  - git remote set-url origin ${GIT_URL}
  - git fetch origin gh-pages:remotes/origin/gh-pages
  - git worktree add -B gh-pages public origin/gh-pages
  - ./hugo

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
