title: 'kstmのブログ'
dist: dist

themeConfig:
  lastUpdated: '最終更新'
  nav:
    - text: 'kstm ホームページ'
      link: 'https://kstm.shinshu-u.ac.jp'
    - text: 'GitHub'
      link: 'https://github.com/kstm-su'

  sidebar:
    - 'aboutus'
    - 'ictsc-2020'
    - 'generate_bacon'
    - 'advent-calendar-2018'
    - 'kstm_network'
    - 'kstm-activity-2017'
    - 'advent-calendar-2017'
    - 'kstmztp20171208'
    - 'isucon7q'
    - '20171029-candle'
    - 'isucon6q'
    - 'bbq-2016'
    - 'kodomo-programming-nagano-2'
    - 'ictsc6'
    - 'icfpc-2016'
    - 'kodomo-programming-nagano-1'
    - 'icpc-2016-tsukuba'
    - 'kodomo-programming-urugi'
